### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by cococolani** [tienlonghungson/ChessEngine#3]
Hello
I am getting error when trying to learn from your code
the errors came from this part : ChessEngine-main\src\chess\piece\Piece.java:143:16
java: illegal start of expression
line 143:16 in piece.java
i am using intelliJ IDE.
Need help
Thanks

**Comment by tienlonghungson** [comment]
@cococolani  Which java version are you using?

**Comment by tienlonghungson** [comment]
@cococolani my first guess is that your current Java version cannot compile the statement:  
         return switch (data[0]) {
            case "P" -> Pawn.parsePawn(data);
            ....
        };
because it's not available in Java 8 if I remember it correctly.
